/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examen1p2_joselagos;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.Set;
import javax.swing.DefaultComboBoxModel;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tonye
 */
public class Admin extends javax.swing.JFrame {

    /**
     * Creates new form Admin
     */
    public Admin() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bntg_Puntaje = new javax.swing.ButtonGroup();
        btng_Genero = new javax.swing.ButtonGroup();
        btng_Mod = new javax.swing.ButtonGroup();
        btng_Genero_mod = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tf_Titulo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta_Descripcion = new javax.swing.JTextArea();
        tf_Valor = new javax.swing.JTextField();
        rb_1 = new javax.swing.JRadioButton();
        rb_2 = new javax.swing.JRadioButton();
        rb_3 = new javax.swing.JRadioButton();
        rb_4 = new javax.swing.JRadioButton();
        rb_5 = new javax.swing.JRadioButton();
        tf_Edicion = new javax.swing.JTextField();
        tf_Autor = new javax.swing.JTextField();
        tf_Año = new javax.swing.JTextField();
        tf_Copias = new javax.swing.JTextField();
        rb_F = new javax.swing.JRadioButton();
        rb_R = new javax.swing.JRadioButton();
        rb_A = new javax.swing.JRadioButton();
        rb_H = new javax.swing.JRadioButton();
        btn_Agregar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        cb_Libro_mod = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        tf_Titulo_m = new javax.swing.JTextField();
        tf_Copias_m = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        ta_Descripcion_m = new javax.swing.JTextArea();
        rb_1_m = new javax.swing.JRadioButton();
        rb_2_m = new javax.swing.JRadioButton();
        rb_3_m = new javax.swing.JRadioButton();
        rb_4_m = new javax.swing.JRadioButton();
        rb_5_m = new javax.swing.JRadioButton();
        tf_Valor_m = new javax.swing.JTextField();
        tf_Autor_m = new javax.swing.JTextField();
        tf_Año_m = new javax.swing.JTextField();
        tf_Edicion_m = new javax.swing.JTextField();
        rb_F_m = new javax.swing.JRadioButton();
        rb_R_m = new javax.swing.JRadioButton();
        rb_A_m = new javax.swing.JRadioButton();
        rb_H_m = new javax.swing.JRadioButton();
        btn_Mod = new javax.swing.JToggleButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        cb_Libreria = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        cb_Delete = new javax.swing.JComboBox<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Agregar Libro");

        jLabel2.setText("Titulo:");

        jLabel3.setText("Descripcion:");

        jLabel4.setText("Puntaje:");

        jLabel5.setText("Copias disponibles:");

        jLabel6.setText("Genero:");

        jLabel7.setText("Valor:");

        jLabel8.setText("Edicion:");

        jLabel9.setText("Autor");

        jLabel10.setText("Año de Publicacion:");

        ta_Descripcion.setColumns(20);
        ta_Descripcion.setRows(5);
        jScrollPane1.setViewportView(ta_Descripcion);

        bntg_Puntaje.add(rb_1);
        rb_1.setText("1");

        bntg_Puntaje.add(rb_2);
        rb_2.setText("2");

        bntg_Puntaje.add(rb_3);
        rb_3.setText("3");

        bntg_Puntaje.add(rb_4);
        rb_4.setText("4");

        bntg_Puntaje.add(rb_5);
        rb_5.setText("5");

        btng_Genero.add(rb_F);
        rb_F.setText("Fantasia");

        btng_Genero.add(rb_R);
        rb_R.setText("Romance");

        btng_Genero.add(rb_A);
        rb_A.setText("Accion");

        btng_Genero.add(rb_H);
        rb_H.setText("Historia");

        btn_Agregar.setText("Agregar");
        btn_Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AgregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel9))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(218, 218, 218)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_Autor, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rb_1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rb_2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rb_3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rb_4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rb_5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_Valor, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tf_Edicion, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_Copias, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_Año, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel6)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(rb_F)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rb_R)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rb_A)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rb_H))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(216, 216, 216)
                        .addComponent(btn_Agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(256, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(tf_Autor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(tf_Año, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tf_Copias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(rb_1)
                    .addComponent(rb_2)
                    .addComponent(rb_3)
                    .addComponent(rb_4)
                    .addComponent(rb_5))
                .addGap(8, 8, 8)
                .addComponent(jLabel6)
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tf_Valor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(tf_Edicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rb_F)
                            .addComponent(rb_R)
                            .addComponent(rb_A)
                            .addComponent(rb_H))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 184, Short.MAX_VALUE)
                .addComponent(btn_Agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        jTabbedPane1.addTab("Agregar", jPanel1);

        cb_Libro_mod.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cb_Libro_mod.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_Libro_modItemStateChanged(evt);
            }
        });
        cb_Libro_mod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_Libro_modActionPerformed(evt);
            }
        });

        jLabel11.setText("Titulo");

        jLabel12.setText("Descripcion");

        jLabel13.setText("Puntaje");

        jLabel14.setText("Copias disponible");

        jLabel15.setText("Genero");

        jLabel16.setText("Valor");

        jLabel17.setText("Edicion");

        jLabel18.setText("Autor");

        jLabel19.setText("Año de publicacion");

        ta_Descripcion_m.setColumns(20);
        ta_Descripcion_m.setRows(5);
        jScrollPane2.setViewportView(ta_Descripcion_m);

        btng_Mod.add(rb_1_m);
        rb_1_m.setText("1");
        rb_1_m.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_1_mActionPerformed(evt);
            }
        });

        btng_Mod.add(rb_2_m);
        rb_2_m.setText("2");

        btng_Mod.add(rb_3_m);
        rb_3_m.setText("3");

        btng_Mod.add(rb_4_m);
        rb_4_m.setText("4");

        btng_Mod.add(rb_5_m);
        rb_5_m.setText("5");

        btng_Genero_mod.add(rb_F_m);
        rb_F_m.setText("Fantasia");

        btng_Genero_mod.add(rb_R_m);
        rb_R_m.setText("Romance");

        btng_Genero_mod.add(rb_A_m);
        rb_A_m.setText("Accion");

        btng_Genero_mod.add(rb_H_m);
        rb_H_m.setText("Historia");

        btn_Mod.setText("Modificar");
        btn_Mod.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ModMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(232, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(rb_1_m)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rb_2_m)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rb_3_m)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rb_4_m)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rb_5_m))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_Copias_m, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cb_Libro_mod, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_Titulo_m, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_Autor_m, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_Año_m, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_Valor_m, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(rb_F_m)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rb_R_m)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rb_A_m)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rb_H_m))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addGap(18, 18, 18)
                                .addComponent(tf_Edicion_m, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(72, 72, 72)
                                .addComponent(btn_Mod)))))
                .addGap(211, 211, 211))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(cb_Libro_mod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(tf_Titulo_m, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addGap(30, 30, 30)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rb_1_m)
                            .addComponent(rb_2_m)
                            .addComponent(rb_3_m)
                            .addComponent(rb_4_m)
                            .addComponent(rb_5_m))))
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(tf_Copias_m, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(tf_Valor_m, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rb_F_m)
                            .addComponent(rb_R_m)
                            .addComponent(rb_A_m)
                            .addComponent(rb_H_m))
                        .addGap(1, 1, 1)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(tf_Autor_m, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tf_Año_m, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel17)
                        .addComponent(tf_Edicion_m, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_Mod)))
                .addContainerGap(163, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Modificar", jPanel2);

        jLabel20.setText("Libros");

        cb_Libreria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cb_Libreria.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_LibreriaItemStateChanged(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Titulo", "Descripcion", "Autor", "Genero", "Edicion", "Puntaje", "Copias disponibles", "Valor", "Año de publicacion"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable1);

        jButton1.setText("Limpiar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jScrollPane3))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cb_Libreria, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(397, 397, 397)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(466, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_Libreria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(145, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Listar", jPanel3);

        cb_Delete.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cb_Delete.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_DeleteItemStateChanged(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Titulo", "Autor", "Edicion", "Genero"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(jTable2);

        jButton2.setText("Eliminar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(cb_Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(212, 212, 212)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(414, 414, 414)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(287, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(cb_Delete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(103, 103, 103)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(163, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Eliminar", jPanel4);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Historial"
            }
        ));
        jScrollPane5.setViewportView(jTable3);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 886, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(98, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Historial", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
        if (jTabbedPane1.getSelectedIndex() == 1) {
            tab = 1;
        }
        if (jTabbedPane1.getSelectedIndex() == 2) {
            tab = 2;
        }
        if (jTabbedPane1.getSelectedIndex() == 3) {
            tab = 3;
        }
    }//GEN-LAST:event_jTabbedPane1StateChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (jTable2.getSelectedRow() >= 0) {
            DefaultTableModel modelo = (DefaultTableModel) jTable2.getModel();
            cb_Libro_mod.remove(jTable2.getSelectedRow());
            cb_Libreria.remove(jTable2.getSelectedRow());
            cb_Delete.remove(jTable2.getSelectedRow());
            modelo.removeRow(jTable2.getSelectedRow());
            jTable2.setModel(modelo);
            //tf_edad_maxima.setText(maxima_edad());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cb_DeleteItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_DeleteItemStateChanged
        if (tab == 3) {
            if (evt.getStateChange() == 3) {
                Libros s = (Libros)cb_Delete.getSelectedItem();
                Object[] newrow = { s.getTitulo(), s.getAutor(), s.getEdicion(), s.getGenero(),};
                DefaultTableModel modelo = (DefaultTableModel) jTable2.getModel();
                modelo.addRow(newrow);
                jTable2.setModel(modelo);
            }
        }
    }//GEN-LAST:event_cb_DeleteItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jTable1.setModel(new javax.swing.table.DefaultTableModel( new Object[][]{},  new String[]{ "Titulo", "Descripcion", "Autor", "Genero", "Edicion", "Puntaje", "Copias disponibles", "Valor", "Año de publicacion"}) {
            Class[] types = new Class[]{ java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Object.class };
            boolean[] canEdit = new boolean[]{
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cb_LibreriaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_LibreriaItemStateChanged
        if (tab == 1) {
            if (evt.getStateChange() == 1) {
                Libros s = (Libros)cb_Libreria.getSelectedItem();
                Object[] newrow = { s.getTitulo(), s.getDescripcion(),  s.getAutor(), s.getGenero(), s.getEdicion(), s.getPuntaje(), s.getCopias(), s.getValor(), s.getPublicacion() };
                DefaultTableModel modelo
                = (DefaultTableModel) jTable1.getModel();
                modelo.addRow(newrow);
                jTable1.setModel(modelo);
            }
        }
    }//GEN-LAST:event_cb_LibreriaItemStateChanged

    private void btn_ModMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ModMouseClicked
        select.setAutor(tf_Autor_m.getText());
        select.setTitulo(tf_Titulo_m.getText());
        select.setPublicacion(Integer.parseInt(tf_Año_m.getText()));
        select.setDescripcion(ta_Descripcion_m.getText());
        if (rb_1_m.isSelected()) {
            select.setPuntaje(1);
        } else if (rb_2_m.isSelected()) {
            select.setPuntaje(2);
        } else if (rb_3_m.isSelected()) {
            select.setPuntaje(3);
        } else if (rb_4_m.isSelected()) {
            select.setPuntaje(4);
        } else if (rb_5_m.isSelected()) {
            select.setPuntaje(5);
        }
        select.setValor(tf_Valor_m.getText());
        select.setCopias(Integer.parseInt(tf_Copias_m.getText()));
        select.setEdicion(tf_Edicion_m.getText());

        if (rb_F_m.isSelected()) {
            select.setGenero("Fantasia");
        } else if (rb_R_m.isSelected()) {
            select.setGenero("Romance");
        } else if (rb_A_m.isSelected()) {
            select.setGenero("Accion");
        } else if (rb_H_m.isSelected()) {
            select.setGenero("Historia");
        }

        JOptionPane.showMessageDialog(this, "El libro ha sido modificado");
        tf_Titulo.setText("");
        tf_Autor.setText("");
        tf_Año.setText("");
        tf_Copias.setText("");
        tf_Edicion.setText("");
        tf_Valor.setText("");
        ta_Descripcion.setText("");
        rb_F.setSelected(true);
        rb_R.setSelected(false);
        rb_A.setSelected(false);
        rb_H.setSelected(false);
        rb_1.setSelected(true);
        rb_2.setSelected(false);
        rb_3.setSelected(false);
        rb_4.setSelected(false);
        rb_5.setSelected(false);
    }//GEN-LAST:event_btn_ModMouseClicked

    private void rb_1_mActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_1_mActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb_1_mActionPerformed

    private void cb_Libro_modActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_Libro_modActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_Libro_modActionPerformed

    private void cb_Libro_modItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_Libro_modItemStateChanged
        if (tab == 1) {
            if (evt.getStateChange() == 1) {
                tf_Titulo_m.setText("");
                ta_Descripcion_m.setText("");
                tf_Copias_m.setText("");
                tf_Valor_m.setText("");
                tf_Autor_m.setText("");
                tf_Año_m.setText("");
                tf_Edicion_m.setText("");
                rb_1_m.setSelected(true);
                rb_2_m.setSelected(false);
                rb_3_m.setSelected(false);
                rb_4_m.setSelected(false);
                rb_5_m.setSelected(false);
                rb_F_m.setSelected(true);
                rb_A_m.setSelected(false);
                rb_R_m.setSelected(false);
                rb_H_m.setSelected(false);

                select = (Libros) cb_Libro_mod.getSelectedItem();
                this.tf_Titulo_m.setText(select.getTitulo());
                this.tf_Autor_m.setText(select.getAutor());
                this.tf_Año_m.setText(Integer.toString(select.getPublicacion()));
                this.tf_Copias_m.setText(Integer.toString(select.getCopias()));
                this.tf_Edicion_m.setText(select.getEdicion());
                this.tf_Valor_m.setText(select.getValor());
                this.ta_Descripcion_m.setText(select.getDescripcion());
                if (select.getPuntaje() == 1) {
                    this.rb_1_m.setSelected(true);
                    this.rb_2_m.setSelected(false);
                    this.rb_3_m.setSelected(false);
                    this.rb_4_m.setSelected(false);
                    this.rb_5_m.setSelected(false);
                } else if (select.getPuntaje() == 2) {
                    this.rb_1_m.setSelected(false);
                    this.rb_2_m.setSelected(true);
                    this.rb_3_m.setSelected(false);
                    this.rb_4_m.setSelected(false);
                    this.rb_5_m.setSelected(false);
                } else if (select.getPuntaje() == 3) {
                    this.rb_1_m.setSelected(false);
                    this.rb_2_m.setSelected(false);
                    this.rb_3_m.setSelected(true);
                    this.rb_4_m.setSelected(false);
                    this.rb_5_m.setSelected(false);
                } else if (select.getPuntaje() == 4) {
                    this.rb_1_m.setSelected(false);
                    this.rb_2_m.setSelected(false);
                    this.rb_3_m.setSelected(false);
                    this.rb_4_m.setSelected(true);
                    this.rb_5_m.setSelected(false);
                } else if (select.getPuntaje() == 5) {
                    this.rb_1_m.setSelected(false);
                    this.rb_2_m.setSelected(false);
                    this.rb_3_m.setSelected(false);
                    this.rb_4_m.setSelected(false);
                    this.rb_5_m.setSelected(true);
                }

                if (select.getGenero().equals("Fantasia")) {
                    this.rb_F_m.setSelected(true);
                    this.rb_A_m.setSelected(false);
                    this.rb_R_m.setSelected(false);
                    this.rb_H_m.setSelected(false);
                } else if (select.getGenero().equals("Romance")) {
                    this.rb_F_m.setSelected(false);
                    this.rb_A_m.setSelected(false);
                    this.rb_R_m.setSelected(true);
                    this.rb_H_m.setSelected(false);
                } else if (select.getGenero().equals("Accion")) {
                    this.rb_F_m.setSelected(false);
                    this.rb_A_m.setSelected(true);
                    this.rb_R_m.setSelected(false);
                    this.rb_H_m.setSelected(false);
                } else if (select.getGenero().equals("Historia")) {
                    this.rb_F_m.setSelected(false);
                    this.rb_A_m.setSelected(false);
                    this.rb_R_m.setSelected(false);
                    this.rb_H_m.setSelected(true);
                }

            }
        }
    }//GEN-LAST:event_cb_Libro_modItemStateChanged

    private void btn_AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AgregarActionPerformed
        String titulo, descripcion, edicion, autor, valor, genero = "";
        int puntaje = 1, copias, año;
        try {
            titulo = tf_Titulo.getText();
            descripcion = ta_Descripcion.getText();
            edicion = tf_Edicion.getText();
            autor = tf_Autor.getText();
            año = Integer.parseInt(tf_Año.getText());
            valor = tf_Valor.getText();
            copias = Integer.parseInt(tf_Copias.getText());

            if (rb_1.isSelected()) {
                puntaje = 1;
            } else if (rb_2.isSelected()) {
                puntaje = 2;
            } else if (rb_2.isSelected()) {
                puntaje = 3;
            } else if (rb_2.isSelected()) {
                puntaje = 4;
            } else if (rb_2.isSelected()) {
                puntaje = 5;
            }

            if (rb_F.isSelected()) {
                genero += "Fantasia";
            } else if (rb_R.isSelected()) {
                genero += "Romance";
            } else if (rb_A.isSelected()) {
                genero += "Accion";
            } else if (rb_H.isSelected()) {
                genero += "Historia";
            }

            Libros x = new Libros(titulo, descripcion, puntaje, copias, genero, valor, edicion, autor, año);
            libreria.add(x);

            DefaultComboBoxModel ll = (DefaultComboBoxModel) cb_Libro_mod.getModel();
            ll.addElement(x);
            cb_Libro_mod.setModel(ll);

            tf_Titulo.setText("");
            tf_Autor.setText("");
            tf_Año.setText("");
            tf_Copias.setText("");
            tf_Edicion.setText("");
            tf_Valor.setText("");
            ta_Descripcion.setText("");
            rb_F.setSelected(true);
            rb_R.setSelected(false);
            rb_A.setSelected(false);
            rb_H.setSelected(false);
            rb_1.setSelected(true);
            rb_2.setSelected(false);
            rb_3.setSelected(false);
            rb_4.setSelected(false);
            rb_5.setSelected(false);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ha ocurrido un error al agregar");
        }
    }//GEN-LAST:event_btn_AgregarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bntg_Puntaje;
    private javax.swing.JButton btn_Agregar;
    private javax.swing.JToggleButton btn_Mod;
    private javax.swing.ButtonGroup btng_Genero;
    private javax.swing.ButtonGroup btng_Genero_mod;
    private javax.swing.ButtonGroup btng_Mod;
    private javax.swing.JComboBox<String> cb_Delete;
    private javax.swing.JComboBox<String> cb_Libreria;
    private javax.swing.JComboBox<String> cb_Libro_mod;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JRadioButton rb_1;
    private javax.swing.JRadioButton rb_1_m;
    private javax.swing.JRadioButton rb_2;
    private javax.swing.JRadioButton rb_2_m;
    private javax.swing.JRadioButton rb_3;
    private javax.swing.JRadioButton rb_3_m;
    private javax.swing.JRadioButton rb_4;
    private javax.swing.JRadioButton rb_4_m;
    private javax.swing.JRadioButton rb_5;
    private javax.swing.JRadioButton rb_5_m;
    private javax.swing.JRadioButton rb_A;
    private javax.swing.JRadioButton rb_A_m;
    private javax.swing.JRadioButton rb_F;
    private javax.swing.JRadioButton rb_F_m;
    private javax.swing.JRadioButton rb_H;
    private javax.swing.JRadioButton rb_H_m;
    private javax.swing.JRadioButton rb_R;
    private javax.swing.JRadioButton rb_R_m;
    private javax.swing.JTextArea ta_Descripcion;
    private javax.swing.JTextArea ta_Descripcion_m;
    private javax.swing.JTextField tf_Autor;
    private javax.swing.JTextField tf_Autor_m;
    private javax.swing.JTextField tf_Año;
    private javax.swing.JTextField tf_Año_m;
    private javax.swing.JTextField tf_Copias;
    private javax.swing.JTextField tf_Copias_m;
    private javax.swing.JTextField tf_Edicion;
    private javax.swing.JTextField tf_Edicion_m;
    private javax.swing.JTextField tf_Titulo;
    private javax.swing.JTextField tf_Titulo_m;
    private javax.swing.JTextField tf_Valor;
    private javax.swing.JTextField tf_Valor_m;
    // End of variables declaration//GEN-END:variables
    ArrayList libreria = new ArrayList();
    Libros select;
    int tab = 0;
}
